-- Criação das tabelas
CREATE TABLE IF NOT EXISTS USUARIOS (
    usu_id INT PRIMARY KEY AUTO_INCREMENT,
    usu_nome VARCHAR(100) NOT NULL,
    usu_email VARCHAR(150) NOT NULL UNIQUE,
    usu_senha VARCHAR(255) NOT NULL,
    usu_data_cadastro DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    usu_tipo VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORIA (
    cat_id INT PRIMARY KEY AUTO_INCREMENT,
    cat_nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS ASSUNTOS (
    asst_id INT PRIMARY KEY AUTO_INCREMENT,
    asst_nome VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS FAQ (
    faq_id INT PRIMARY KEY AUTO_INCREMENT,
    usu_id INT NOT NULL,
    faq_pergunta VARCHAR(255) NOT NULL,
    faq_resposta VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS NOTICIAS (
    not_id INT PRIMARY KEY AUTO_INCREMENT,
    usu_id INT NOT NULL,
    not_titulo VARCHAR(50) NOT NULL,
    not_conteudo VARCHAR(255) NOT NULL,
    not_imagem VARCHAR(255),
    not_data_publicacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS INF_JOGO (
    inf_id INT PRIMARY KEY AUTO_INCREMENT,
    cat_id INT NOT NULL,
    usu_id INT NOT NULL,
    inf_titulo VARCHAR(50) NOT NULL,
    inf_descricao VARCHAR(500) NOT NULL,
    inf_imagem VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS SUPORTE (
    sup_id INT PRIMARY KEY AUTO_INCREMENT,
    usu_id INT NOT NULL,
    asst_id INT NOT NULL,
    sup_mensagem VARCHAR(500) NOT NULL,
    sup_status VARCHAR(50) NOT NULL,
    sup_data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    sup_email VARCHAR(150) NOT NULL,
    sup_nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMPARTILHAMENTO (
    comp_id INT PRIMARY KEY AUTO_INCREMENT,
    not_id INT NOT NULL,
    comp_plataforma VARCHAR(100) NOT NULL,
    comp_data DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
