DROP TABLE IF EXISTS COMPARTILHAMENTO;
DROP TABLE IF EXISTS SUPORTE;
DROP TABLE IF EXISTS INF_JOGO;
DROP TABLE IF EXISTS NOTICIAS;
DROP TABLE IF EXISTS FAQ;
DROP TABLE IF EXISTS ASSUNTOS;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS USUARIOS;
