-- Definição dos relacionamentos
ALTER TABLE FAQ ADD CONSTRAINT fk_faq_usuario FOREIGN KEY (usu_id) REFERENCES USUARIOS(usu_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE NOTICIAS ADD CONSTRAINT fk_noticias_usuario FOREIGN KEY (usu_id) REFERENCES USUARIOS(usu_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE COMPARTILHAMENTO ADD CONSTRAINT fk_compartilhamento_noticia FOREIGN KEY (not_id) REFERENCES NOTICIAS(not_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE INF_JOGO ADD CONSTRAINT fk_infjogo_categoria FOREIGN KEY (cat_id) REFERENCES CATEGORIA(cat_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE INF_JOGO ADD CONSTRAINT fk_infjogo_usuario FOREIGN KEY (usu_id) REFERENCES USUARIOS(usu_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE SUPORTE ADD CONSTRAINT fk_suporte_usuario FOREIGN KEY (usu_id) REFERENCES USUARIOS(usu_id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE SUPORTE ADD CONSTRAINT fk_suporte_assunto FOREIGN KEY (asst_id) REFERENCES ASSUNTOS(asst_id) ON DELETE CASCADE ON UPDATE CASCADE;
